version: "3.8"

# docker-compose is used so data in mongodb doesn't get lost even when container get killed
services:
  mongodb:
    image : mongo
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped

volumes:
  mongodb-data: