version: "3.8"

services:
  mongodb:
    image : mongo
    container_name: mongodb
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27027:27027
    restart: unless-stopped

volumes:
  mongodb-data: